version: '3.9'

services:
  selenoid:
    image: aerokube/selenoid:latest-release
    volumes:
      - "./config:/etc/selenoid"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./video:/opt/selenoid/video"
      - "./logs:/opt/selenoid/logs"
    environment:
      - OVERRIDE_VIDEO_OUTPUT_DIR=/opt/selenoid/video
    command: [ "-conf", "/etc/selenoid/browsers.json", "-container-network", "jenkins-network" ]
    ports:
      - "4444:4444"
    networks:
      - test-network

  selenoid-ui:
    image: aerokube/selenoid-ui:latest-release
    depends_on:
      - selenoid
    ports:
      - "8090:8080"
    command: [ "--selenoid-uri", "http://selenoid:4444" ]
    networks:
      - test-network

  tests:
    image: maven:3.9-eclipse-temurin-17
    volumes:
      - ".:/app"
      - "maven-repo:/root/.m2"
    working_dir: /app
    command: mvn clean test -Dselenium.hub=http://selenoid:4444/wd/hub -Dgrid=true -Dbrowser=chrome
    networks:
      - test-network
    depends_on:
      - selenoid

volumes:
  maven-repo:

networks:
  test-network:
    name: jenkins-network